### ISSUE TITLE
[PEDAGO STATUS] "Logout of" someone bug

### ISSUE THREAD

**Issue by simontraww1** [epitest/epitest#1]
# **Uniquement** lorsqu'on est connecté à une autre personne
Lorsqu'on ne clique pas sur l'intitulé **Log Out** mais qu'on appuie sur le bouton (là ou il n'y a pas le texte **"log out"**, sur la partie grise du bouton) ça **réfresh** sur la même page, en revanche si j'appuie sur le texte **"log out" **ça marche instant.

**Comment by paullaffitte** [comment]
On avait remarqué le bug mais sans réussir à définir les conditions exactes de reproductions. Merci pour les précisions. On s'en occupe.
